create table if not exists public.ai_reply_suggestions (
  id bigint generated by default as identity primary key,
  post_id text not null,
  group_id text,
  post_url text,
  target_source text,
  target_source_id text,
  customer_name text,
  intent_label text,
  customer_need text,
  buying_stage text,
  urgency text,
  confidence numeric,
  recommended_approach text,
  suggested_replies jsonb not null default '[]'::jsonb,
  raw_ai jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_reply_suggestions_post_id_idx
  on public.ai_reply_suggestions (post_id);

create index if not exists ai_reply_suggestions_created_at_idx
  on public.ai_reply_suggestions (created_at desc);

alter table public.ai_reply_suggestions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_reply_suggestions'
      and policyname = 'allow anon insert ai reply suggestions'
  ) then
    create policy "allow anon insert ai reply suggestions"
    on public.ai_reply_suggestions
    for insert
    to anon
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_reply_suggestions'
      and policyname = 'allow anon select ai reply suggestions'
  ) then
    create policy "allow anon select ai reply suggestions"
    on public.ai_reply_suggestions
    for select
    to anon
    using (true);
  end if;
end $$;

create table if not exists public.business_profiles (
  id text primary key default 'default',
  business_name text,
  phone text,
  address text,
  why_choose_us text,
  extra_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists business_profiles_set_updated_at on public.business_profiles;
create trigger business_profiles_set_updated_at
before update on public.business_profiles
for each row execute function public.set_updated_at();

alter table public.business_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'business_profiles'
      and policyname = 'allow anon select business profile'
  ) then
    create policy "allow anon select business profile"
    on public.business_profiles
    for select
    to anon
    using (id = 'default');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'business_profiles'
      and policyname = 'allow anon insert business profile'
  ) then
    create policy "allow anon insert business profile"
    on public.business_profiles
    for insert
    to anon
    with check (id = 'default');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'business_profiles'
      and policyname = 'allow anon update business profile'
  ) then
    create policy "allow anon update business profile"
    on public.business_profiles
    for update
    to anon
    using (id = 'default')
    with check (id = 'default');
  end if;
end $$;
