create table if not exists public.ai_reply_suggestions (
  id bigint generated by default as identity primary key,
  post_id text not null,
  group_id text,
  post_url text,
  target_source text,
  target_source_id text,
  customer_name text,
  intent_label text,
  customer_need text,
  buying_stage text,
  urgency text,
  confidence numeric,
  recommended_approach text,
  suggested_replies jsonb not null default '[]'::jsonb,
  raw_ai jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists ai_reply_suggestions_post_id_idx
  on public.ai_reply_suggestions (post_id);

create index if not exists ai_reply_suggestions_created_at_idx
  on public.ai_reply_suggestions (created_at desc);

alter table public.ai_reply_suggestions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_reply_suggestions'
      and policyname = 'allow anon insert ai reply suggestions'
  ) then
    create policy "allow anon insert ai reply suggestions"
    on public.ai_reply_suggestions
    for insert
    to anon
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_reply_suggestions'
      and policyname = 'allow anon select ai reply suggestions'
  ) then
    create policy "allow anon select ai reply suggestions"
    on public.ai_reply_suggestions
    for select
    to anon
    using (true);
  end if;
end $$;

create table if not exists public.comment_logs (
  id bigint generated by default as identity primary key,
  staff_id text,
  staff_name text,
  staff_username text,
  facebook_user_id text,
  post_id text not null,
  group_id text,
  post_url text,
  comment_text text not null,
  comment_image_url text,
  comment_id text,
  page_id text,
  status text not null check (status in ('success', 'failed')),
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists comment_logs_created_at_idx
  on public.comment_logs (created_at desc);

create index if not exists comment_logs_staff_id_idx
  on public.comment_logs (staff_id);

create index if not exists comment_logs_post_id_idx
  on public.comment_logs (post_id);

alter table public.comment_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'comment_logs'
      and policyname = 'allow anon insert comment logs'
  ) then
    create policy "allow anon insert comment logs"
    on public.comment_logs
    for insert
    to anon
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'comment_logs'
      and policyname = 'allow anon select comment logs'
  ) then
    create policy "allow anon select comment logs"
    on public.comment_logs
    for select
    to anon
    using (true);
  end if;
end $$;

alter table public.comment_logs
  add column if not exists comment_image_url text;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'comment-images',
  'comment-images',
  true,
  8388608,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'allow anon upload comment images'
  ) then
    create policy "allow anon upload comment images"
    on storage.objects
    for insert
    to anon
    with check (bucket_id = 'comment-images');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'allow anon select comment images'
  ) then
    create policy "allow anon select comment images"
    on storage.objects
    for select
    to anon
    using (bucket_id = 'comment-images');
  end if;
end $$;

create table if not exists public.post_comment_summaries (
  id bigint generated by default as identity primary key,
  post_id text not null,
  group_id text,
  post_url text,
  post_author text,
  post_text text,
  comment_count integer not null default 0,
  fetched_comment_count integer not null default 0,
  comment_authors_count integer not null default 0,
  summary text,
  sentiment text,
  urgency text,
  main_topics jsonb not null default '[]'::jsonb,
  customer_intents jsonb not null default '[]'::jsonb,
  top_questions jsonb not null default '[]'::jsonb,
  notable_comments jsonb not null default '[]'::jsonb,
  lead_signals jsonb not null default '[]'::jsonb,
  recommended_action text,
  spam_or_noise_count integer not null default 0,
  raw_ai jsonb not null default '{}'::jsonb,
  created_by_staff_id text,
  created_by_staff_name text,
  created_at timestamptz not null default now()
);

create index if not exists post_comment_summaries_post_id_idx
  on public.post_comment_summaries (post_id);

create index if not exists post_comment_summaries_created_at_idx
  on public.post_comment_summaries (created_at desc);

alter table public.post_comment_summaries enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'post_comment_summaries'
      and policyname = 'allow anon insert post comment summaries'
  ) then
    create policy "allow anon insert post comment summaries"
    on public.post_comment_summaries
    for insert
    to anon
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'post_comment_summaries'
      and policyname = 'allow anon select post comment summaries'
  ) then
    create policy "allow anon select post comment summaries"
    on public.post_comment_summaries
    for select
    to anon
    using (true);
  end if;
end $$;

create or replace view public.comment_daily_staff_stats
with (security_invoker = true)
as
select
  (created_at at time zone 'Asia/Ho_Chi_Minh')::date as comment_date,
  coalesce(nullif(staff_id, ''), 'unknown') as staff_id,
  coalesce(nullif(staff_name, ''), 'Chưa có tên') as staff_name,
  coalesce(nullif(staff_username, ''), 'unknown') as staff_username,
  coalesce(nullif(facebook_user_id, ''), 'unknown') as facebook_user_id,
  count(distinct post_id) as successful_post_count,
  count(*) as successful_comment_count,
  min(created_at) as first_success_at,
  max(created_at) as last_success_at
from public.comment_logs
where status = 'success'
group by
  (created_at at time zone 'Asia/Ho_Chi_Minh')::date,
  coalesce(nullif(staff_id, ''), 'unknown'),
  coalesce(nullif(staff_name, ''), 'Chưa có tên'),
  coalesce(nullif(staff_username, ''), 'unknown'),
  coalesce(nullif(facebook_user_id, ''), 'unknown');

grant select on public.comment_daily_staff_stats to anon, authenticated;

create table if not exists public.business_profiles (
  id text primary key default 'default',
  business_name text,
  phone text,
  address text,
  why_choose_us text,
  extra_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists business_profiles_set_updated_at on public.business_profiles;
create trigger business_profiles_set_updated_at
before update on public.business_profiles
for each row execute function public.set_updated_at();

alter table public.business_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'business_profiles'
      and policyname = 'allow anon select business profile'
  ) then
    create policy "allow anon select business profile"
    on public.business_profiles
    for select
    to anon
    using (id = 'default');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'business_profiles'
      and policyname = 'allow anon insert business profile'
  ) then
    create policy "allow anon insert business profile"
    on public.business_profiles
    for insert
    to anon
    with check (id = 'default');
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'business_profiles'
      and policyname = 'allow anon update business profile'
  ) then
    create policy "allow anon update business profile"
    on public.business_profiles
    for update
    to anon
    using (id = 'default')
    with check (id = 'default');
  end if;
end $$;
